<script>
    import logo from "$lib/img/logo.png";
    import product from "$lib/img/prod.png";
    import about from "$lib/img/about.png";
    import partner from "$lib/img/partner.png";
    import contact from "$lib/img/contact.png";
    // categorii :medii de cultura,cromogene,teste pcr,echipamente de laborator,despre noi,produse,contacte,parteneri
</script>

<header class="header slide-in-right">
    <img src={logo} alt="" class="logo" />
    <div class="nav">
        <div class="dual">
            <img src={product} alt="" class="icon" />
            <a href="" class="list">Produse</a>
        </div>
        <div class="dual">
            <img src={about} alt="" class="icon" />
            <a href="" class="list">Despre Noi</a>
        </div>
        <div class="dual">
            <img src={partner} alt="" class="icon" />
            <a href="" class="list">Parteneri</a>
        </div>
        <div class="dual">
            <img src={contact} alt="" class="icon" />
            <a href="" class="list">Contacte</a>
        </div>
    </div>
</header>

<style>
    .dual {
        display: flex;
        align-items: center;
        margin-inline: 10px;
    }
    .icon {
        width: 24px;
        margin-right: 2px;
    }
    .list {
        color: black;
        font-size: 18px;
        font-weight: 600;
    }
    .nav {
        display: flex;
        align-items: center;
    }
    .logo {
        width: 150px;
        cursor: pointer;
    }
    .header {
        display: flex;
        align-items: center;
        width: 100%;
        height: 70px;
        background-color: white;
        justify-content: space-around;
    }
    .slide-in-right {
        -webkit-animation: slide-in-right 0.5s
            cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: slide-in-right 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2024-1-18 0:51:13
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    @-webkit-keyframes slide-in-right {
        0% {
            -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
            transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes slide-in-right {
        0% {
            -webkit-transform: translateX(1000px);
            transform: translateX(1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
            transform: translateX(0);
            opacity: 1;
        }
    }
</style>
