<script>
    import Header from "../lib/Header.svelte";
    import background from "$lib/img/render.jpg";
</script>

<img src={background} alt="" class="background slide-in-left" />
<main class="app">
    <Header />
</main>

<style>
    .app {
        width: 100%;
        position: relative;
        overflow: hidden;
    }
    .background {
        width: 100%;
        height: 100vh;
        position: fixed;
        object-fit: cover;
    }
    .slide-in-left {
        -webkit-animation: slide-in-left 0.5s
            cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
        animation: slide-in-left 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2024-1-18 0:52:7
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    @-webkit-keyframes slide-in-left {
        0% {
            -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
            transform: translateX(0);
            opacity: 1;
        }
    }
    @keyframes slide-in-left {
        0% {
            -webkit-transform: translateX(-1000px);
            transform: translateX(-1000px);
            opacity: 0;
        }
        100% {
            -webkit-transform: translateX(0);
            transform: translateX(0);
            opacity: 1;
        }
    }
</style>
